PREFIX ifcext: <http://www.semanticweb.org/aaron/ontologies/2022/1/ifcextension#>

INSERT{
    ifcext:IfcEntities rdfs:subClassOf expr:SELECT ;
                       rdf:type owl:Class .
    ?value rdfs:subClassOf ifcext:IfcEntities .
} WHERE {
    VALUES ?value {
    ifc:IfcDraughtingCalloutRelationship
    ifc:IfcProfileProperties
    ifc:IfcReinforcementBarProperties
    ifc:IfcSectionProperties
    ifc:IfcSectionReinforcementProperties
    ifc:IfcPhysicalQuantity
    ifc:IfcMaterialProperties
    ifc:IfcRelaxation
    ifc:IfcMaterial
    ifc:IfcMaterialClassificationRelationship
    ifc:IfcMaterialLayer
    ifc:IfcMaterialLayerSet
    ifc:IfcMaterialLayerSetUsage
    ifc:IfcMaterialList
    ifc:IfcLightDistributionData
    ifc:IfcLightIntensityDistribution
    ifc:IfcPresentationLayerAssignment
    ifc:IfcIrregularTimeSeriesValue
    ifc:IfcTimeSeries
    ifc:IfcTimeSeriesValue
    ifc:IfcTimeSeriesReferenceRelationship
    ifc:IfcProductRepresentation
    ifc:IfcRepresentation
    ifc:IfcRepresentationContext
    ifc:IfcShapeAspect
    ifc:IfcDerivedUnit
    ifc:IfcDerivedUnitElement
    ifc:IfcDimensionalExponents
    ifc:IfcMeasureWithUnit
    ifc:IfcMonetaryUnit
    ifc:IfcNamedUnit
    ifc:IfcUnitAssignment
    ifc:IfcProperty
    ifc:IfcPropertyDependencyRelationship
    ifc:IfcPropertyEnumeration
    ifc:IfcColourSpecification
    ifc:IfcPreDefinedItem
    ifc:IfcBoundaryCondition
    ifc:IfcStructuralConnectionCondition
    ifc:IfcStructuralLoad
    ifc:IfcCurveStyleFont
    ifc:IfcCurveStyleFontAndScaling
    ifc:IfcCurveStyleFontPattern
    ifc:IfcPresentationStyle
    ifc:IfcPresentationStyleAssignment
    ifc:IfcSurfaceStyleLighting
    ifc:IfcSurfaceStyleRefraction
    ifc:IfcSurfaceStyleShading
    ifc:IfcSurfaceStyleWithTextures
    ifc:IfcSurfaceTexture
    ifc:IfcTextStyleForDefinedFont
    ifc:IfcTextStyleTextModel
    ifc:IfcTextStyleWithBoxCharacteristics
    ifc:IfcProfileDef
    ifc:IfcApplication
    ifc:IfcOwnerHistory
    ifc:IfcTable
    ifc:IfcTableRow
    ifc:IfcTextureCoordinate
    ifc:IfcTextureVertex
    ifc:IfcVertexBasedTextureMap
    ifc:IfcRoot
    ifc:IfcRepresentationItem
    ifc:IfcRepresentationMap
    ifc:IfcConnectionGeometry
    ifc:IfcGridAxis
    ifc:IfcObjectPlacement
    ifc:IfcVirtualGridIntersection
    ifc:IfcClassification
    ifc:IfcClassificationItem
    ifc:IfcClassificationItemRelationship
    ifc:IfcClassificationNotation
    ifc:IfcClassificationNotationFacet
    ifc:IfcDocumentElectronicFormat
    ifc:IfcDocumentInformation
    ifc:IfcDocumentInformationRelationship
    ifc:IfcExternalReference
    ifc:IfcLibraryInformation
    ifc:IfcCalendarDate
    ifc:IfcCoordinatedUniversalTimeOffset
    ifc:IfcDateAndTime
    ifc:IfcLocalTime
    ifc:IfcAppliedValue
    ifc:IfcAppliedValueRelationship
    ifc:IfcCurrencyRelationship
    ifc:IfcReferencesValueDocument
    ifc:IfcConstraint
    ifc:IfcConstraintAggregationRelationship
    ifc:IfcConstraintClassificationRelationship
    ifc:IfcConstraintRelationship
    ifc:IfcPropertyConstraintRelationship
    ifc:IfcApproval
    ifc:IfcApprovalActorRelationship
    ifc:IfcApprovalPropertyRelationship
    ifc:IfcApprovalRelationship
    ifc:IfcActorRole
    ifc:IfcAddress
    ifc:IfcOrganization
    ifc:IfcOrganizationRelationship
    ifc:IfcPerson
    ifc:IfcPersonAndOrganization}
}